FILEID_MAP = {
    "files/analisis_de_las_respuestas_al_cuestionar": "api/bibliografia/ANaLISIS_DE_LAS_RESPUESTAS_AL_CUESTIONAR.pdf",
    "files/caso_jade": "api/bibliografia/CASO JADE.pdf",
    "files/casos": "api/bibliografia/CASOS.pdf",
    "files/cd_diana": "api/bibliografia/CD DIANA.pdf",
    "files/cd_graciela_celener": "api/bibliografia/CD Graciela Celener.pdf",
    "files/cd_pulsiones_y_defensas_en_patologías_desvalimiento": "api/bibliografia/CD pulsiones y defensas en patologías desvalimiento.pdf",
    "files/cuadro_proye_-_catexias_positivas_y_negativas": "api/bibliografia/Cuadro proye - Catexias positivas y negativas.pdf",
    "files/cuestionario_desiderativo_aplicado_a_niños2": "api/bibliografia/Cuestionario desiderativo aplicado a niños2.pdf",
    "files/cuestionario_desiderativo-sneiderman3": "api/bibliografia/Cuestionario desiderativo-Sneiderman3.pdf",
    "files/indicadores-psicopatologicos_-_cd": "api/bibliografia/Indicadores-Psicopatologicos - CD.pdf",
    "files/o_questionario_desiderativo_fundamentos": "api/bibliografia/O_questionario_desiderativo_fundamentos.pdf",
    "files/ocampo_arzeno": "api/bibliografia/Ocampo Arzeno.pdf",
    "files/preconsciente_y_su_relación_con_el_lenguaje": "api/bibliografia/Preconsciente y su relación con el lenguaje.pdf",
    "files/psicodiagnostico_clinico_93-117": "api/bibliografia/Psicodiagnostico Clinico 93-117.pdf",
    "files/sneiderman_2011-cuestionario": "api/bibliografia/Sneiderman_2011-Cuestionario.pdf",
    "files/teorÍa,_tÉcnica_y_aplicaciÓn": "api/bibliografia/TEORÍA, TÉCNICA Y APLICACIÓN.pdf",
    "files/una_contribución_a_la_interpretación_del_cuestionario_desiderativo": "api/bibliografia/Una contribución a la interpretación del Cuestionario Desiderativo.pdf",
    "files/vinculo_hostil": "api/bibliografia/Vinculo hostil.pdf",
    "files/bullying": "api/bibliografia/bullying.pdf",
    "files/criterios_de_interpretación": "api/bibliografia/criterios de interpretación.pdf",
    "files/niños_latentes": "api/bibliografia/niños latentes.pdf",
}
